language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: wz8y8vfVyZlyBFM6dgyYF3NJt6vg9GnT/BN3e9zYFqWF9Moi3FYXH956L9z58f0+Wk/gxPvprMURGFsKET0ztwirlhMWinrQdWWM6GsclXcCzMCJ+GYADmkYLI6W8jrcvSpfpKr61VV27EHZj4zEM8DdL94BpDR0E8IAjJ6sCiY=
  - secure: lQAQLD0KV3WmEY5nm1DfubeDKmUSWClBEP9D9OuEw/psHNhSvI3eG8ylzghSAMWf5uxzX0gq7h36YKvPtCA4zTAWnK0wSiGHXchthk+PABL2ioR+Q0XpzfQ3jEokY0wWil1Xj+DJZyIEX2wY7Zbxpyd6F68VaCWcBmtoubOU8PY=
